spring:
  application:
    name: wise-task-plugin
  datasource:
    url: jdbc:postgresql://localhost:5432/wise_task_plugin
    username: wise_task_plugin
    password: wise_task_plugin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          use_streams_for_binary: false

path-plugin: "./plugins/"
plugin-validation-limit: 30000000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE

grpc:
  service:
    graph:
      port: 6565
      host: "localhost"
  port: 6566
server:
  port: 8081