spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wise_task_plugin
    username: wise_task_plugin
    password: wise_task_plugin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true

path-plugin: "./plugins/"
plugin-validation-limit: 30000000

grpc:
  service:
    graph:
      port: 6565
  port: 6566
server:
  port: 8081