openapi: 3.0.0
info:
  version: 1.0.0
  title: Wise-task plugin api

paths:
  /plugin:
    get:
      summary: Get all plugins
      operationId: getPlugins
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/plugin"
    post:
      summary: Create external plugin
      operationId: createExternalPlugin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                pluginInfo:
                  $ref: "#/components/schemas/plugin"
                pluginFile:
                  type: string
                  format: binary
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/plugin"

  /plugin/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string

    get:
      summary: Get plugin by id
      operationId: getPlugin
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/plugin"
    put:
      summary: Update plugin by id
      operationId: updatePlugin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                pluginInfo:
                  $ref: "#/components/schemas/plugin"
                pluginFile:
                  type: string
                  format: binary
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/plugin"

    post:
      summary: Verify plugin by id
      operationId: verifyPlugin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                payload:
                  $ref: "#/components/schemas/requestPayload"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                properties:
                  result:
                    type: string
    delete:
      summary: Delete plugin by id
      operationId: deletePlugin
      responses:
        200:
          description: "OK"

components:
  schemas:
    pluginType:
      type: string
      enum: [ graph ]
    color:
      type: string
      enum: [ "red", "green", "blue" ]

    plugin:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        fileName:
          type: string
        authorId:
          type: string
        pluginType:
          $ref: "#/components/schemas/pluginType"
        isInternal:
          type: boolean

    requestPayload:
      type: object
      properties:
        pluginType:
          $ref: "#/components/schemas/pluginType"
        mainPayload:
          oneOf:
            - $ref: "#/components/schemas/graph"
          discriminator:
            propertyName: objectType
            mapping:
              graph: "#/components/schemas/graph"
        additionalData:
          oneOf:
            - $ref: "#/components/schemas/graph"
            - $ref: "#/components/schemas/handWrittenAnswer"
          discriminator:
            propertyName: objectType
            mapping:
              graph: "#/components/schemas/graph"
              handWrittenAnswer: "#/components/schemas/handWrittenAnswer"

    handWrittenAnswer:
      type: object
      properties:
        data:
          type: string
        objectType:
          type: string

    graph:
      type: object
      properties:
        vertexCount:
          type: integer
        edgeCount:
          type: integer
        isDirect:
          type: boolean
        edges:
          type: array
          items:
            $ref: "#/components/schemas/edge"
        vertices:
          type: array
          items:
            $ref: "#/components/schemas/vertex"
        objectType:
          type: string
    edge:
      type: object
      properties:
        source:
          type: integer
        target:
          type: integer
        color:
            $ref: "#/components/schemas/color"
        weight:
          type: integer
        label:
          type: string
    vertex:
      type: object
      properties:
        id:
          type: integer
        color:
          $ref: "#/components/schemas/color"
        weight:
          type: integer
        label:
          type: string
        xCoordinate:
          type: integer
        yCoordinate:
          type: integer
